redis:
  active: false
weChat:
  APP_ID: wxa02348cd5ec17d28
  APP_SECRET: ENC(QcmW6fG+sKsLxFa3k9AtAtcNs+QHsFXFuns+Xb2MR1gIv7kM+gwKQoftoMvO/S9o)
  INTERFACE_TOKEN: 123qwe
  INTERFACE_URL: http://chety.mynatapp.cc/api/v1/wechat/portal
  JS_DOMAIN:
  WEB_AUTH_DOMAIN:
spring:
  profiles:
    active: dev
#logging:
#  level: info
