profiles:
  active: dev

redis:
  active: false
weChat:
      APP_ID: wxa02348cd5ec17d28
      APP_SECRET: ENC(QcmW6fG+sKsLxFa3k9AtAtcNs+QHsFXFuns+Xb2MR1gIv7kM+gwKQoftoMvO/S9o)
      INTERFACE_TOKEN: 123qwe
      INTERFACE_URL: http://chety.mynatapp.cc/api/v1/wechat/portal
      JS_DOMAIN:
      WEB_AUTH_DOMAIN:

spring:
  redis:
    #redis数据库，默认是0
    database: 0
    #redis服务器地址
    host: 120.79.27.209
    #redis服务端口，默认6379
    port: 6379
    #redis密码，默认为空
    password: ENC(saFOB3bDz+pe2xcxGSfc5USnZ+OvQhKY)

local:
    active: true
